# Optimal features from RFECV analysis
OPTIMAL_FEATURES = [
    'home_pregame_elo',
    'away_pregame_elo',
    'away_off_pass_success',
    'away_def_pass_success',
    'home_off_std_downs_ppa',
    'away_off_std_downs_ppa',
    'away_def_pass_downs_ppa',
    'home_comp_off_ppa',
    'home_comp_def_ppa',
    'away_comp_off_ppa',
    'away_comp_def_ppa',
    'away_comp_pass_ppa',
    'home_comp_epa',
    'home_comp_success',
    'away_comp_epa',
    'away_comp_success',
    'away_comp_ypp',
    'home_clean_off_ppa',
    'home_clean_def_ppa',
    'away_clean_off_ppa',
    'away_clean_def_ppa',
]
